In [25]:
import cv2
orgimg = cv2.imread('/home/dheeraj/my_projects/my_project_env/practice/motion_detector/Face Dtection/test.jpg')
img = cv2.resize(orgimg, (0,0), fx=0.5, fy=0.5)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [26]:
# cv2.imshow('Original image',orgimg)
# cv2.imshow('Gray image', gray)
  
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [27]:
face_cascade = cv2.CascadeClassifier('/home/dheeraj/my_projects/my_project_env/practice/motion_detector/haarcascade_frontalface_alt2.xml')
faces = face_cascade.detectMultiScale(gray, 1.3, 5)
for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y), (x+w, y+h), (255,0,0), 2)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
import numpy as np
import cv2
face_cascade = cv2.CascadeClassifier('/home/dheeraj/my_projects/my_project_env/practice/motion_detector/haarcascade_smile.xml')

image = cv2.imread('/home/dheeraj/my_projects/my_project_env/practice/motion_detector/Face Dtection/IMG_9258.JPG')
img = cv2.resize(image, (0,0), fx=0.17, fy=0.23)
grayImage = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 
faces = face_cascade.detectMultiScale(grayImage)
 
print(type(faces))
 
if len(faces) == 0:
    print("No faces found")
 
else:
    print(faces)
    print(faces.shape)
    print("Number of faces detected: " + str(faces.shape[0]))
 
    for (x,y,w,h) in faces:
        cv2.rectangle(img, (x,y), (x+w, y+h), (255,0,0),2)
 
    cv2.rectangle(image, ((0,img.shape[0] -25)),(270, img.shape[0]), (255,255,255), -1)
    cv2.putText(img, "Number of faces detected: " + str(faces.shape[0]), (0,img.shape[0] -10), cv2.FONT_HERSHEY_TRIPLEX, 1,  (255,255,255), 2)
 
    cv2.imshow('Image with faces',img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[237 206  43  21]
 [497 151  42  21]
 [ 55  92  41  20]
 [206  32  43  21]
 [950 212  44  22]
 [693   5  44  22]
 [168 212  64  32]
 [960 227  39  19]
 [532  41  60  30]
 [947  15  42  21]
 [807  19  47  24]
 [800  48  48  24]
 [286 132 203 102]
 [588 173  43  22]
 [316  27  47  23]
 [908 101  72  36]
 [234  10  70  35]
 [561  91 107  53]
 [873  52  54  27]
 [754 224 116  58]
 [475 101  76  38]
 [ 62 241 112  56]
 [349 247  64  32]
 [ 51 102  78  38]
 [242 161  64  32]
 [917  32  73  37]
 [707  33  87  43]
 [651  66  95  48]
 [471 151  88  44]
 [212 101  93  46]
 [ 94  75 138  69]
 [708   3  83  41]
 [672 107 254 127]
 [688  56  87  44]
 [498  14  80  40]
 [922 180  87  44]
 [ 39 138  91  46]
 [ 44   4  92  46]
 [ 12 132  77  39]
 [640 235 107  54]
 [571 245  81  40]
 [280  58 169  84]
 [886  33  95  48]
 [195 151  92  46]
 [ 89 143  88  43]
 [ 17  24 121  60]
 [418 289  60  30]
 [225  71 141  70]
 [664  26 148  74]
 [ 96 194 258 129]
 [633  48 193  96]
 [226 2