In [1]:
import cv2
orgimg = cv2.imread('/home/dheeraj/my_projects/my_project_env/practice/motion_detector/Face Dtection/test.jpg')
img = cv2.resize(orgimg, (0,0), fx=0.5, fy=0.5)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


In [2]:
# cv2.imshow('Original image',orgimg)
# cv2.imshow('Gray image', gray)
  
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [ ]:
face_cascade = cv2.CascadeClassifier('/home/dheeraj/my_projects/my_project_env/practice/motion_detector/haarcascade_frontalface_alt2.xml')
faces = face_cascade.detectMultiScale(gray, 1.3, 5)
for (x,y,w,h) in faces:
    cv2.rectangle(img, (x,y), (x+w, y+h), (255,0,0), 2)
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import numpy as np
import cv2
face_cascade = cv2.CascadeClassifier('/home/dheeraj/my_projects/my_project_env/practice/motion_detector/haarcascade_frontalface_alt2.xml')

image = cv2.imread('/home/dheeraj/my_projects/my_project_env/practice/motion_detector/Face Dtection/IMG_9261.JPG')
img = cv2.resize(image, (0,0), fx=0.24, fy=0.24)
grayImage = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 
faces = face_cascade.detectMultiScale(grayImage)
 
print(type(faces))
 
if len(faces) == 0:
    print("No faces found")
 
else:
    print(faces)
    print(faces.shape)
    print("Number of faces detected: " + str(faces.shape[0]))
 
    for (x,y,w,h) in faces:
        cv2.rectangle(img, (x,y), (x+w, y+h), (255,0,0),2)
 
    cv2.rectangle(image, ((0,img.shape[0] -25)),(270, img.shape[0]), (255,255,255), -1)
    cv2.putText(img, "Number of faces detected: " + str(faces.shape[0]), (0,img.shape[0] -10), cv2.FONT_HERSHEY_TRIPLEX, 1,  (255,255,255), 2)
 
    cv2.imshow('Image with faces',img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[ 310  182   62   62]
 [ 678  227   52   52]
 [ 858  235   54   54]
 [ 761  267   50   50]
 [ 456  217   58   58]
 [ 583  239   51   51]
 [ 939  343   67   67]
 [ 771  357   65   65]
 [1032  260   65   65]
 [1144  256   71   71]
 [ 764  494   72   72]
 [ 565  522   65   65]
 [ 944  690   37   37]]
(13, 4)
Number of faces detected: 13
